AlbumFotos/AlbumFotos/Controllers/AlbunsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AlbumFotos.Models;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Hosting;

namespace AlbumFotos.Controllers
{
    public class AlbunsController : Controller
    {
        private readonly Contexto _context;
        private readonly IHostingEnvironment _hostingEnvironment;

        public AlbunsController(Contexto context, IHostingEnvironment hostingEnvironment)
        {
            _context = context;
            _hostingEnvironment = hostingEnvironment;
        }

        // GET: Albuns
        public async Task<IActionResult> Index()
        {
            return View(await _context.Albuns.ToListAsync());
        }

        // GET: Albuns/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var album = await _context.Albuns
                .FirstOrDefaultAsync(m => m.AlbumId == id);
            if (album == null)
            {
                return NotFound();
            }

            return View(album);
        }

        // GET: Albuns/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Albuns/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AlbumId,Destino,FotoTopo,Inicio,Fim")] Album album, IFormFile arquivo)
        {
            if (ModelState.IsValid)
            {
                var linkUpload = Path.Combine(_hostingEnvironment.WebRootPath, "Imagens");

                if(arquivo != null)
                {
                    using (var fileStream = new FileStream(Path.Combine(linkUpload, arquivo.FileName), FileMode.Create))
                    {
                        await arquivo.CopyToAsync(fileStream);
                        album.FotoTopo = "~/Imagens/" + arquivo.FileName;
                    }
                }

                _context.Add(album);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(album);
        }

        // GET: Albuns/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var album = await _context.Albuns.FindAsync(id);
            if (album == null)
            {
                return NotFound();
            }

            TempData["FotoTopo"] = album.FotoTopo;

            return View(album);
        }

        // POST: Albuns/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AlbumId,Destino,FotoTopo,Inicio,Fim")] Album album, IFormFile arquivo)
        {
            if (id != album.AlbumId)
            {
                return NotFound();
            }

            if (String.IsNullOrEmpty(album.FotoTopo))
                album.FotoTopo = TempData["FotoTopo"].ToString();

            if (ModelState.IsValid)
            {
                try
                {
                    var linkUpload = Path.Combine(_hostingEnvironment.WebRootPath, "Imagens");

                    if(arquivo != null)
                    {
                        using (var fileStream = new FileStream(Path.Combine(linkUpload, arquivo.FileName), FileMode.Create))
                        {
                            await arquivo.CopyToAsync(fileStream);
                            album.FotoTopo = "~/Imagens/" + arquivo.FileName;
                        }
                    }

                    _context.Update(album);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AlbumExists(album.AlbumId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(album);
        }        

        // POST: Albuns/Delete/5
        [HttpPost]
        public async Task<JsonResult> Delete(int AlbumId)
        {
            var album = await _context.Albuns.FindAsync(AlbumId);
            IEnumerable<string> links = _context.Imagens.Where(i => i.AlbumId == AlbumId).Select(i => i.Link);

            foreach(var link in links)
            {
                var linkImagem = link.Replace("~", "wwwroot");
                System.IO.File.Delete(linkImagem);
            }

            _context.Imagens.RemoveRange(_context.Imagens.Where(x => x.AlbumId == AlbumId));

            string linkFotoAlbum = album.FotoTopo;
            linkFotoAlbum = linkFotoAlbum.Replace("~", "wwwroot");
            System.IO.File.Delete(linkFotoAlbum);
            _context.Albuns.Remove(album);
            await _context.SaveChangesAsync();
            return Json("Album excluído com sucesso");
        }

        private bool AlbumExists(int id)
        {
            return _context.Albuns.Any(e => e.AlbumId == id);
        }
    }
}

AlbumFotos/AlbumFotos/ViewComponents/ImagemViewComponent.cs
using AlbumFotos.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AlbumFotos.ViewComponents
{
    public class ImagemViewComponent : ViewComponent
    {
        private readonly Contexto _contexto;

        public ImagemViewComponent(Contexto contexto)
        {
            _contexto = contexto;
        }

        public async Task<IViewComponentResult> InvokeAsync(int id)
        {
            return View(await _contexto.Imagens.Where(x => x.AlbumId == id).ToListAsync());
        }
    }
}

AlbumFotos/AlbumFotos/Views/Albuns/Create.cshtml
@model AlbumFotos.Models.Album

@{
    ViewData["Title"] = "Novo album";
}

<div class="formulario">
    <div class="container">

        <div class="titulo">
            <h5>Album</h5> 
            <hr />
        </div>

        <div class="row">
            <div class="col-md-4">
                <form asp-action="Create" enctype="multipart/form-data">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    
                    <div class="input-field">
                        <label asp-for="Destino" class="control-label"></label>
                        <input asp-for="Destino" class="form-control" />
                        <span asp-validation-for="Destino" class="text-danger"></span>
                    </div>

                    <img id="imagem" src="#" alt="Foto"/>
                    <div class="file-field input-field">
                        <div class="btn-small">
                            <span>Selecione o arquivo</span>
                            <input asp-for="FotoTopo" class="form-control" type="file" name="arquivo" onchange="CarregarImagem(this)" />
                            <span asp-validation-for="FotoTopo" class="text-danger"></span>
                        </div>
                        <div class="file-path-wrapper">
                            <input class="file-path-wrapper validate" type="text" placeholder="Faça o upload da foto"/>
                        </div>
                    </div>

                    <div class="input-field">
                        <label asp-for="Inicio" class="control-label"></label>
                        <input asp-for="Inicio" class="form-control datepicker" type="text" />
                        <span asp-validation-for="Inicio" class="text-danger"></span>
                    </div>
                    <div class="input-field">
                        <label asp-for="Fim" class="control-label"></label>
                        <input asp-for="Fim" class="form-control datepicker" type="text"/>
                        <span asp-validation-for="Fim" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Salvar" class="btn-small" /> &nbsp;
                        <a asp-action="Index" class="btn-small grey darken-3">Voltar</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}


    <script>
        $(document).ready(function () {
            $("#imagem").hide();

            $('.datepicker').datepicker({
                autoclose: true,
                format: 'dd/mm/yyyy',
                defaultDate: new Date(),
                setDefaultDate: true,
                disableWeekends: false,
                showDaysInNextAndPreviousMonths: true,
                showMonthAfterYear: true,
                firstDay: 0,
                showClearBtn: true,
                i18n: {
                    cancel: 'Cancelar',
                    clear: 'Limpar',
                    done: 'Ok',
                    previousMonth: '‹',
                    nextMonth: '›',
                    months: [
                        'Janeiro',
                        'Fevereiro',
                        'Março',
                        'Abril',
                        'Maio',
                        'Junho',
                        'Julho',
                        'Agosto',
                        'Setembro',
                        'Outubro',
                        'Novembro',
                        'Dezembro'
                    ],

                    monthsShort: [
                        'Jan',
                        'Fev',
                        'Mar',
                        'Abr',
                        'Mai',
                        'Jun',
                        'Jul',
                        'Ago',
                        'Set',
                        'Out',
                        'Nov',
                        'Dez'
                    ],

                    weekdays: [
                        'Domingo',
                        'Segunda-feira',
                        'Terça-feira',
                        'Quarta-feira',
                        'Quinta-feira',
                        'Sexta-feira',
                        'Sábado'
                    ],

                    weekdaysShort: [
                        'Dom',
                        'Seg',
                        'Ter',
                        'Qua',
                        'Qui',
                        'Sex',
                        'Sab'
                    ],

                    weekdaysAbbrev: ['D', 'S', 'T', 'Q', 'Q', 'S', 'S']
                }

            });
        });

        function CarregarImagem(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                $("#imagem").show();

                reader.onload = function (e) {
                    $("#imagem").attr('src', e.target.result).width(250).height(250);
                }
            }

            reader.readAsDataURL(input.files[0]);
        }
    </script>

}

AlbumFotos/AlbumFotos/Views/Albuns/Details.cshtml
@model AlbumFotos.Models.Album

@{
    ViewData["Title"] = "Detalhes do album " + Model.Destino;
}

<div class="album">
    <div class="foto">
        <div class="container">
            <div class="texto">
                <h2 class="white-text">@Html.DisplayFor(model => model.Destino)</h2>
                <h5 class="white-text">@Html.DisplayFor(model => model.Inicio) a @Html.DisplayFor(model => model.Fim)</h5>
            </div>
        </div>
    </div>

    <div>
        <hr />
        <h5 class="center">Fotos de(o) @Model.Destino</h5>
        <hr />
        <div class="linkImagem hide">@Model.FotoTopo</div>
    </div>

    <div class="botoes">
        <a asp-controller="Imagens" asp-action="Create" asp-route-id="@Model.AlbumId" class="btn-small">Nova foto</a> |
        <a asp-action="Index" class="btn-small grey darken-3">Voltar</a>
    </div>
</div>


@await  Component.InvokeAsync("Imagem", new { id = Model.AlbumId})

@section Scripts{
    <script>
    var linkImagem = $(".linkImagem").text();
    var url = "/" + linkImagem;

    $(document).ready(function () {
        $(".foto").css("background-image", 'url("@Url.Content(Model.FotoTopo)")');
    });
    </script>
}

AlbumFotos/AlbumFotos/Views/Albuns/Edit.cshtml
@model AlbumFotos.Models.Album

@{
    ViewData["Title"] = "Atualizar " + Model.Destino;
}


<div class="formulario">
    <div class="container">
        <div class="titulo">
            <h5>Atualizar Album @Model.Destino</h5>
            <hr />
        </div>
        <div class="row">
            <div class="col-md-4">
                <form asp-action="Edit" enctype="multipart/form-data">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="AlbumId" />

                    <div class="input-field">
                        <label asp-for="Destino" class="control-label"></label>
                        <input asp-for="Destino" class="form-control" />
                        <span asp-validation-for="Destino" class="text-danger"></span>
                    </div>

                    @if (Model.FotoTopo != null)
                    {
                        <img id="imagem" src="@Url.Content(Model.FotoTopo)" width="250" height="250" alt="Foto" />
                    }
                    else
                    {
                        <img id="imagem" src="#" width="250" height="250" alt="Foto" />
                    }


                    <div class="file-field input-field">
                        <div class="btn-small">
                            <span>Selecione o arquivo</span>
                            <input asp-for="FotoTopo" class="form-control" type="file" name="arquivo" onchange="CarregarImagem(this)" />
                            <span asp-validation-for="FotoTopo" class="text-danger"></span>
                        </div>
                        <div class="file-path-wrapper">
                            <input class="file-path-wrapper validate" type="text" placeholder="Faça o upload da foto" />
                        </div>
                    </div>

                    <div class="input-field">
                        <label asp-for="Inicio" class="control-label"></label>
                        <input asp-for="Inicio" class="form-control datepicker" type="text" />
                        <span asp-validation-for="Inicio" class="text-danger"></span>
                    </div>
                    <div class="input-field">
                        <label asp-for="Fim" class="control-label"></label>
                        <input asp-for="Fim" class="form-control datepicker" type="text" />
                        <span asp-validation-for="Fim" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Atualizar" class="btn-small" /> &nbsp;
                        <a asp-action="Index" class="btn-small grey darken-3">Voltar</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
        $(document).ready(function () {           

            $('.datepicker').datepicker({
                autoclose: true,
                format: 'dd/mm/yyyy',
                defaultDate: new Date(),
                setDefaultDate: true,
                disableWeekends: false,
                showDaysInNextAndPreviousMonths: true,
                showMonthAfterYear: true,
                firstDay: 0,
                showClearBtn: true,
                i18n: {
                    cancel: 'Cancelar',
                    clear: 'Limpar',
                    done: 'Ok',
                    previousMonth: '‹',
                    nextMonth: '›',
                    months: [
                        'Janeiro',
                        'Fevereiro',
                        'Março',
                        'Abril',
                        'Maio',
                        'Junho',
                        'Julho',
                        'Agosto',
                        'Setembro',
                        'Outubro',
                        'Novembro',
                        'Dezembro'
                    ],

                    monthsShort: [
                        'Jan',
                        'Fev',
                        'Mar',
                        'Abr',
                        'Mai',
                        'Jun',
                        'Jul',
                        'Ago',
                        'Set',
                        'Out',
                        'Nov',
                        'Dez'
                    ],

                    weekdays: [
                        'Domingo',
                        'Segunda-feira',
                        'Terça-feira',
                        'Quarta-feira',
                        'Quinta-feira',
                        'Sexta-feira',
                        'Sábado'
                    ],

                    weekdaysShort: [
                        'Dom',
                        'Seg',
                        'Ter',
                        'Qua',
                        'Qui',
                        'Sex',
                        'Sab'
                    ],

                    weekdaysAbbrev: ['D', 'S', 'T', 'Q', 'Q', 'S', 'S']
                }

            });
        });

        function CarregarImagem(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();              

                reader.onload = function (e) {
                    $("#imagem").attr('src', e.target.result).width(250).height(250);
                }
            }

            reader.readAsDataURL(input.files[0]);
        }
    </script>
}

AlbumFotos/AlbumFotos/Views/Albuns/Index.cshtml
@model IEnumerable<AlbumFotos.Models.Album>

@{
    ViewData["Title"] = "Albuns";
}


<div class="listaDestinos">
    <div class="container">
        <p>
            <a asp-action="Create" class="waves-effect waves-light btn-small">Novo album</a>
        </p>
        <table class="table striped highlight hover responsive-table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Destino)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Inicio)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Fim)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Destino)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Inicio)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Fim)
                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.AlbumId" class="btn-small blue darken-2">Atualizar</a> |
                            <a asp-action="Details" asp-route-id="@item.AlbumId" class="btn-small orange darken-4">Fotos</a> |
                            <a class="btn-small red darken-4 modal-trigger" data-target="modal1" onclick="Excluir(@item.AlbumId)">Excluir</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<div id="modal1" class="modal">
    <div class="modal-content">
        <h4>Confirmar exclusão</h4>
        <p>Deseja prosseguir com a exclusão ?</p>
    </div>
    <div class="modal-footer">
        <a class="modal-close waves-effect waves-green btn-flat btnConfirmar">Sim</a>
        <a class="modal-close waves-effect waves-green btn-flat">Não</a>
    </div>
</div>

<script>
    function Excluir(AlbumId) {
        $(".modal").modal();

        $(".btnConfirmar").on('click', function () {
            $.ajax({
                url: '/Albuns/Delete',
                type: 'POST',
                data: { AlbumId: AlbumId },
                success: function () {
                    location.reload();
                    $(".modal").modal('close');
                }
            })
        });
    }
</script>